% Visualization script for the validation Figure 5D-F

close all
clear all
clc

%% differences
close all
load('./project/results/results_subpop_final.mat')
load_plot_settings

parameters.name = {'log_{10}(k_1)',...
'log_{10}(k_2)',...
'log_{10}(k_4)',...
'log_{10}(k_5)',...
'log_{10}(\beta_{k_3[TrkA]_{0,1}})',...
'log_{10}(\beta_{k_3[TrkA]_{0,2}})',...
'log_{10}(\beta_{c_P^{1,2}[Erk]_{0,1}})',...
'log_{10}(\sigma_{T,1})',...
'log_{10}(\sigma_{T,2})',...
'log_{10}(\sigma_{E})',...
'log_{10}(\sigma_{TE})',...
'log_{10}(o_P^{1})',...
'log_{10}(c_P^{2})',...
'log_{10}(o_P^{2})',...
'log_{10}(c_P^{3})',...
'log_{10}(o_P^{3})',...
'log_{10}(c_P^{4})',...
'log_{10}(o_P^{4})',...
'log_{10}(c_T^{3}/k_3)',...
'log_{10}(o_T^{3})',...
'log_{10}(c_E^{4}/c_P^{1})',...
'log_{10}(o_E^{4})',...
'log_{10}(\sigma_{P,noise}^{1})',...
'log_{10}(\sigma_{P,noise}^{2})',...
'log_{10}(\sigma_{P,noise}^{3})',...
'log_{10}(\sigma_{P,noise}^{4})',...
'log_{10}(\sigma_{T,noise}^{3})',...
'log_{10}(\sigma_{E,noise}^{4})',...
'w'};

options.plot.A.plot_type = 1;
options.plot.A.lw = 1;
options.plot.MS.lw = 0.8;
options.plot.MS.plot_type = 1;
options.plot.P.lw = 0.8;
options.plot.A.lw = 0.8;


plotParameterProfiles(parameters,[],[],[1:16],options.plot)
legend('off')
for i = 1:16
    subplot(4,4,i)
ylabel({'likelihood'; 'ratio'},'fontsize',fs)
set(gca,'fontsize',fs)
end

 set(gcf, 'PaperUnits','centimeters', 'PaperPosition',[0 0 16 9])
 print('-dpdf',['./project/figures/subpop_profiles_1'])

plotParameterProfiles(parameters,[],[],[17:parameters.number],options.plot)

legend('off')
for i = 1:13
    subplot(4,4,i)
ylabel({'likelihood'; 'ratio'},'fontsize',fs)
set(gca,'fontsize',fs)
end

set(gcf, 'PaperUnits','centimeters', 'PaperPosition',[0 0 16 9])
print('-dpdf',['./project/figures/subpop_profiles_2'])

